export const COLOURS = {
  white: "#ffffff",
  black: "#000000",
  green: "#00AC76",
  red: "#C04345",
  blue: "#55BCF6",
  // backgroundLight: "#F0F0F3",
  backgroundMedium: "#B9B9B9",
  backgroundDark: "#777777",
  backgroundLight: "#E8EAED",
};
export const Items = [
  {
    id: 1,
    category: "product",
    mentorName: "Mentor dummy 1",
    productPrice: 2000,
    description: "lorem",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    productImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 2,
    category: "product",
    mentorName: "Mentor dummy 2",
    productPrice: 2000,
    description: "tes",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    productImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 3,
    category: "product",
    mentorName: "Mentor dummy 3",
    productPrice: 2000,
    description: "tes",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    productImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 4,
    category: "product",
    mentorName: "Mentor dummy 3",
    productPrice: 2000,
    description: "tes",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    productImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 5,
    category: "product",
    mentorName: "Mentor dummy 3",
    productPrice: 2000,
    description: "tes",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    productImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 6,
    category: "product",
    mentorName: "Mentor dummy 3",
    productPrice: 2000,
    description: "tes",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    productImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 7,
    category: "product",
    mentorName: "Mentor dummy 3",
    productPrice: 2000,
    description: "tes",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    productImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 8,
    category: "product",
    mentorName: "Mentor dummy 3",
    productPrice: 2000,
    description: "tes",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    productImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 9,
    category: "product",
    mentorName: "Mentor dummy 3",
    productPrice: 2000,
    description: "tes",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    productImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 10,
    category: "product",
    mentorName: "Mentor dummy 3",
    productPrice: 2000,
    description: "tes",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    productImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
];
