export const COLOURS = {
  white: "#ffffff",
  black: "#000000",
  green: "#00AC76",
  red: "#C04345",
  blue: "#55BCF6",
  // backgroundLight: "#F0F0F3",
  backgroundMedium: "#B9B9B9",
  backgroundDark: "#777777",
  backgroundLight: "#E8EAED",
};
export const Items = [
  {
    id: 1,
    category: "product",
    mentorName: "Steven Christiansen",
    productPrice: 35000,
    description: "Saya lulusan di Harvard University dan mengambil jurusan Matematika. Saya dapat membantu lebih dalam dan mengajarkan anda seputar jurusan Matematika.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/Mentor1.jpg"),
    productImageList: [
      require("../database/assets/products/Mentor1.jpg"),
      require("../database/assets/products/Mentor1.jpg"),
      require("../database/assets/products/Mentor1.jpg"),
    ],
  },
  {
    id: 2,
    category: "product",
    mentorName: "Carlos Bayson",
    productPrice: 19000,
    description: "Saya sedang menjalankan kuliah di Binus University. Keinginan saya adalah mengajarkan kalian mata pelajaran Matematika.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/Mentor2.jpg"),
    productImageList: [
      require("../database/assets/products/Mentor2.jpg"),
      require("../database/assets/products/Mentor2.jpg"),
      require("../database/assets/products/Mentor2.jpg"),
    ],
  },
  {
    id: 3,
    category: "product",
    mentorName: "Christine Gabriella",
    productPrice: 20000,
    description: "Saya adalah seorang guru di Sekolah Negeri 1. Saya ingin membantu siapa saja yang ingin belajar mengenai Bahasa Indonesia dan Bahasa Inggris",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/Mentor3.jpg"),
    productImageList: [
      require("../database/assets/products/Mentor3.jpg"),
      require("../database/assets/products/Mentor3.jpg"),
      require("../database/assets/products/Mentor3.jpg"),
    ],
  },
  {
    id: 4,
    category: "product",
    mentorName: "Gaby Vania",
    productPrice: 33500,
    description: "Saya sedang berkuliah di Massachusetts Institute of Technology. Saya dapat mengajarkan dan membantu anda untuk memulai pelajaran Fisika secara basic maupun tidak.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/Mentor4.jpg"),
    productImageList: [
      require("../database/assets/products/Mentor4.jpg"),
      require("../database/assets/products/Mentor4.jpg"),
      require("../database/assets/products/Mentor4.jpg"),
    ],
  },
  {
    id: 5,
    category: "product",
    mentorName: "Kevin Joenathan",
    productPrice: 25000,
    description: "Saya berlatar belakang pendidikan di Universitas Indonesia. Saya ingin membantu anda yang kesusahan pada mata pelajaran Fisika, Kimia, atau Biologi.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/Mentor5.jpg"),
    productImageList: [
      require("../database/assets/products/Mentor5.jpg"),
      require("../database/assets/products/Mentor5.jpg"),
      require("../database/assets/products/Mentor5.jpg"),
    ],
  },
  {
    id: 6,
    category: "product",
    mentorName: "James Christiansen",
    productPrice: 15000,
    description: "Mengajar seseorang adalah keinginan saya pada generasi ini. Saya adalah guru di sekolah Mutiara Bangsa 1. Saya akan mengajarkan anda seputar pelajaran Biologi secara keseluruhan.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/Mentor6.jpg"),
    productImageList: [
      require("../database/assets/products/Mentor6.jpg"),
      require("../database/assets/products/Mentor6.jpg"),
      require("../database/assets/products/Mentor6.jpg"),
    ],
  },
  {
    id: 7,
    category: "product",
    mentorName: "Evelyn Felita",
    productPrice: 22000,
    description: "Saya adalah mahasiswa lulusan S2 di Universitas Indonesia. Banyak sekali orang yang ingin belajar mengenai Matematika. Saya ingin mengajarkan mereka yang minat kepada Matematika.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/Mentor7.jpg"),
    productImageList: [
      require("../database/assets/products/Mentor7.jpg"),
      require("../database/assets/products/Mentor7.jpg"),
      require("../database/assets/products/Mentor7.jpg"),
    ],
  },
  {
    id: 8,
    category: "product",
    mentorName: "Jessica Angel",
    productPrice: 25000,
    description: "I am an English teacher and have taught for 3 years at English First (EF). I can help you learn English from basic to expert.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/Mentor8.jpg"),
    productImageList: [
      require("../database/assets/products/Mentor8.jpg"),
      require("../database/assets/products/Mentor8.jpg"),
      require("../database/assets/products/Mentor8.jpg"),
    ],
  },
  {
    id: 9,
    category: "product",
    mentorName: "Karina Jennie",
    productPrice: 21500,
    description: "Saya adalah seorang dosen. Saya telah mengajar selama 5 tahun. Keinginan saya adalah mengajar mata pelajaran Kimia untuk orang yang menginginkannya.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/Mentor9.jpg"),
    productImageList: [
      require("../database/assets/products/Mentor9.jpg"),
      require("../database/assets/products/Mentor9.jpg"),
      require("../database/assets/products/Mentor9.jpg"),
    ],
  },
  {
    id: 10,
    category: "product",
    mentorName: "Michelle Vanessa",
    productPrice: 21500,
    description: "Saya sedang berkuliah di Binus University. Cita-cita saya adalah membantu bangsa ini dengan cara mengajarkan mereka yang ingin belajar Matematika.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/Mentor10.jpg"),
    productImageList: [
      require("../database/assets/products/Mentor10.jpg"),
      require("../database/assets/products/Mentor10.jpg"),
      require("../database/assets/products/Mentor10.jpg"),
    ],
  },
];
