export const COLOURS = {
  white: "#ffffff",
  black: "#000000",
  green: "#00AC76",
  red: "#C04345",
  blue: "#55BCF6",
  // backgroundLight: "#F0F0F3",
  backgroundMedium: "#B9B9B9",
  backgroundDark: "#777777",
  backgroundLight: "#E8EAED",
};
export const Items = [
  {
    id: 1,
    category: "product",
    mentorName: "Carlos Bayson",
    productPrice: 35000,
    description: "Saya lulusan di Harvard University dan mengambil jurusan Matematika. Saya dapat membantu lebih dalam dan mengajarkan anda seputar jurusan Matematika.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/id1.jpg"),
    productImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 2,
    category: "product",
    mentorName: "Chris James",
    productPrice: 24000,
    description: "Saya adalah seorang dosen. Saya telah mengajar selama 5 tahun. Keinginan saya adalah mengajar mata pelajaran Kimia untuk orang yang menginginkannya.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    productImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 3,
    category: "product",
    mentorName: "Gabriella Vania",
    productPrice: 22000,
    description: "Saya berlatar belakang pendidikan di Universitas Indonesia. Saya ingin membantu anda yang kesusahan pada mata pelajaran Fisika, Kimia, atau Biologi.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    productImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 4,
    category: "product",
    mentorName: "Felicia Celine",
    productPrice: 33500,
    description: "Saya sedang berkuliah di Massachusetts Institute of Technology. Saya dapat mengajarkan dan membantu anda untuk memulai pelajaran Fisika secara basic maupun tidak.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    poductImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 5,
    category: "product",
    mentorName: "Steven Christiansen",
    productPrice: 15000,
    description: "Mengajar seseorang adalah keinginan saya pada generasi ini. Saya adalah guru di sekolah Mutiara Bangsa 1. Saya akan mengajarkan anda seputar pelajaran Biologi secara keseluruhan.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    poductImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 6,
    category: "product",
    mentorName: "Kevin Joenathan",
    productPrice: 18000,
    description: "I am an English teacher and have taught for 3 years at English First (EF). I can help you learn English from basic to expert.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    poductImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 7,
    category: "product",
    mentorName: "Christine Marcella",
    productPrice: 20000,
    description: "Saya sedang berkuliah di Binus University. Cita-cita saya adalah membantu bangsa ini dengan cara mengajarkan mereka yang ingin belajar Matematika.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    poductImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 8,
    category: "product",
    mentorName: "Evelyn Angel",
    productPrice: 18000,
    description: "Saya adalah seorang guru di Sekolah Negeri 1. Saya ingin membantu siapa saja yang ingin belajar mengenai Bahasa Indonesia dan Bahasa Inggris.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    poductImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 9,
    category: "product",
    mentorName: "Lisa Sarah",
    productPrice: 25000,
    description: "Saya adalah mahasiswa lulusan S2 di Universitas Indonesia. Banyak sekali orang yang ingin belajar mengenai Matematika. Saya akan membimbing mereka yang benar-benar ingin belajar.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    poductImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
  {
    id: 10,
    category: "product",
    mentorName: "Michelle Audrey",
    productPrice: 23500,
    description: "Saya sedang menjalankan kuliah di Binus University. Keinginan saya adalah mengajarkan kalian mata pelajaran Matematika.",
    isOff: false,
    ofpercentage: 10,
    productImage: require("../database/assets/products/eclairs.png"),
    poductImageList: [
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
      require("../database/assets/products/eclairs.png"),
    ],
  },
];
